### PR TITLE
New Validators

### PR DESCRIPTION
**Pull request by micheleangioni**
Hello!

* Type: new feature

**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/incubator/blob/master/CONTRIBUTING.md)?
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I wrote some tests for this PR.

Small description of change:

After presenting [my Validators package](https://github.com/micheleangioni/phalcon-validators) to the community, [I was asked](https://forum.phalconphp.com/discussion/16055/phalconvalidators-package) to create a Pull Requests to Incubator.

Many tests are present, I've also updated the readme files.

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
@micheleangioni Could you please fix PSR-related errors?

**Comment by micheleangioni** [comment]
@sergeyklay I should have now fixed the PSR-related errors

**Comment by micheleangioni** [comment]
Fixed!

**Comment by sergeyklay** [comment]
Thank you

**Comment by Jurigag** [comment]
@micheleangioni if could have some time add here checks for making it working with multiple field, like:

```php
$validation->add(['field1', 'field2'], new AlphaCompleteValidator([
    'message' => [
        'field1' => 'message for field 1',
        'field2' => 'message for field 2'
]);
```

For more just check phalcon repository and built-in validators in `Phalcon\Validation\Validator` namespace

**Comment by micheleangioni** [comment]
@sergeyklay welcome!

@Jurigag Interesting improvement suggestion, I'll take a look

**Pull request merged**
