### PR TITLE
Added createIfNotExist function

### PR DESCRIPTION
**Pull request by an8val66**
Hello!

* Type: bug fix | new feature
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/incubator/blob/master/CONTRIBUTING.md)?
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I wrote some tests for this PR.

Small description of change:
I tried using this function did not work, so it was just changing the findandmodify function to findoneandupdate.

Thanks

### CODE REVIEW

**Comment by sergeysviridenko** [comment]
@an8val66 this code looks like the original method in `Phalcon\Mvc\Collection`. Could you provide a bit more information?

**Comment by an8val66** [comment]
Exactly only that the original code does not work with the mongo driver in php 7.0. It contains only a small change to fit the code that was already created for the new driver

**Comment by CameronHall** [comment]
@an8val66 can you please write a test for this?

**Comment by cottton** [comment]
I dont like this one.
`createIfNotExist` - i would expect to create the current model if it not exists (by id).

The criteria thing should not be part of the framework imo.
This is something a user should check | add to his code.

**Comment by CameronHall** [comment]
@cottton this is precisely the intention of the Phalcon Incubator. The Incubator is for things that add functionality/value to Phalcon, but don't exactly fit in with the goals of the Framework.

@niden did you want to weigh in here?

**Comment by cottton** [comment]
@CameronHall As far i understood the incubator 
we add things here that later gets implemented into cphlacon.

Forget it - that said i looked into cphalcon and there is already the `createIfNotExist` method.
Well ... not my decisoin - **but why overriding it then?**

BTW: `if ($status == null) ` should be `if ($status === null) `

**Comment by an8val66** [comment]
Guys the my intention here was get the existing method and add here for work with MongoDB driver. The method exist, the big work is not mine, i maked one ctrl+c and ctrl+v and change the methods for MongoDB

**Comment by niden** [comment]
Thank you @an8val66

**Pull request merged**
