### PR TITLE
Http addition

### PR DESCRIPTION
**Pull request by Kachit**

### CODE REVIEW

**Comment by sergeyklay** [comment]
> 207 Multi-Status (WebDAV; RFC 4918)
> 208 Already Reported (WebDAV; RFC 5842)
> 226 IM Used (RFC 3229)
> 308 Permanent Redirect (RFC 7538)

...

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by Kachit** [comment]
ok I add this codes

**Comment by Kachit** [comment]
@sergeyklay tell me please what`s problem with this pull request ?

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
