### PR TITLE
Translate Adapter for multi-column csv

### PR DESCRIPTION
**Pull request by challet**
Hello!

* Type: new feature

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/incubator/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: adding a multi-column csv adapter for the translations.
* CSV example (blank spaces added for readability):
```csv
#ignored;     en_US;  fr_FR;   es_ES
label_street; street; rue;     calle
label_car;    car;    voiture; coche
label_home;   home;   maison;  casa
```
* PHP example : 
```php
// the constructor is inherited from Phalcon\Translate\Adapter\Csv
$titles_translater = new Phalcon\Translate\Adapter\MultiCsv([
    'content' => "{$config->langDir}/titles.csv"
]);
$titles_translater->setLocale('es_ES');
echo $titles_translater->query('label_home'); // string 'casa'
```

It might remain a check to be done about the *ArrayAccess* interface (inherited from *Phalcon\Translate\Adapter\Csv*)

### CODE REVIEW

**Comment by challet** [comment]
Looks like the last commit (upgrading codeception) fixed [this error](https://travis-ci.org/phalcon/incubator/jobs/501157944#L1207) but broke [something else](https://travis-ci.org/phalcon/incubator/jobs/501159776#L1241).

**Comment by sergeyklay** [comment]
@challet Looks solid. Could you fix tests?

**Comment by challet** [comment]
@sergeyklay finally done.

**Comment by sergeyklay** [comment]
Thank you

**Comment by challet** [comment]
You're welcome

**Pull request merged**
