### PR TITLE
Added ::setOption ::setOptions CURLOPT_XXX alias

### PR DESCRIPTION
**Pull request by cottton**
Addded simple check if given option key is a curlopt_xxx string

### CODE REVIEW

**Comment by sergeyklay** [comment]
@cottton

**Comment by sergeyklay** [comment]
I will keep this open for a day or two to allow other contributors a chance to speak up, and to take a fresh look at it later. But at the moment it seems good to me.

**Comment by cottton** [comment]
Sure. Should have no impact to any users out there because normal behaviour still exists.
Btw i say this solution at phinx https://github.com/robmorgan/phinx/blob/master/src/Phinx/Db/Adapter/MysqlAdapter.php#L107

Pretty much the same except they forgot to unset the alias :)

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
