### PR TITLE
Update Smarty.php

### PR DESCRIPTION
**Pull request by tmihalik**

### CODE REVIEW

**Comment by tmihalik** [comment]
"\Phalcon\Mvc\View\Simple" unfortunately not implemented from "\Phalcon\Mvc\ViewInterface"

**Comment by iGusev** [comment]
I dont agree with commit.  This onstructor can take any class with the implementation of `\Phalcon\Mvc\ViewInterface`

For example (from [docs](https://github.com/phalcon/incubator/tree/master/Library/Phalcon/Mvc/View/Engine)): 
```php
//Setting up the view component
$di->set('view', function() {

    $view = new \Phalcon\Mvc\View();

    $view->setViewsDir('../app/views/');

    $view->registerEngines(
        array(".tpl" => 'Phalcon\Mvc\View\Engine\Smarty')
    );

    return $view;
});
```

**Comment by iGusev** [comment]
Anywhere in the docs specified as the return value interface, not implementation.

**Comment by endeveit** [comment]
I agree with @iGusev

**Pull request closed without merging**
