### PR TITLE
Issue #426. Ability to add node to the list of its children.

### PR DESCRIPTION
**Pull request by temuri416**

### CODE REVIEW

**Comment by sergeyklay** [comment]
Looks good to me. What do you think about tests?

**Comment by temuri416** [comment]
You're asking me whether I'd like to write a test suite for NestetSet behaviour?

**Comment by sergeyklay** [comment]
Yep :)

I do not insist, but it would be very cool.

**Comment by temuri416** [comment]
:) I'm all for it. I'll see if I can find time on the weekend.

**Comment by sergeyklay** [comment]
Okay. I think it is safe to merge. What do you think?

**Comment by temuri416** [comment]
Yep, I tested the new flag locally and it does what it should. Thanks!

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
