### PR TITLE
Validator mongoId

### PR DESCRIPTION
**Pull request by Kachit**

### CODE REVIEW

**Comment by sergeyklay** [comment]
> Phalcon\Validation\Exception: Mongo extension is not available

Add to .travis.yml
```yaml
services:
  - mongodb
```

**Comment by sergeyklay** [comment]
@Kachit Also please add something like this in tests for all other developers:

```php
protected function setUp()
{
    if (!extension_loaded('mongo')) {
        $this->markTestSkipped(
          'The MySQLi extension is not available.'
        );
    }
}
```

**Comment by Kachit** [comment]
ok I fix it

**Comment by sergeyklay** [comment]
Also please amend README and squash commits to keep the history clean.

**Comment by sergeyklay** [comment]
Travis CI has preinstalled  `php5-mongo` extension.
For enabling `php5-mongo` (extension not server):

create `tests/travis/mongo.ini`
```ini
extension=mongo.so
```
then add to .travis.yml
```yaml
before_install:
  - pecl channel-update pecl.php.net
  - (CFLAGS="-O1 -g3 -fno-strict-aliasing"; pecl install yaml < /dev/null &)
  - phpenv config-add "tests/travis/mongo.ini" # <---- this
```

**Comment by Kachit** [comment]
done

**Comment by sergeyklay** [comment]
Okay. Now just squash please all commits into a single commit to keep the history clean.

**Comment by sergeyklay** [comment]
@Kachit

**Comment by Kachit** [comment]
Sorry. I needed to sleep. I finish this job today.

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
