### PR TITLE
add config loader factory

### PR DESCRIPTION
**Pull request by Kachit**

### CODE REVIEW

**Comment by sergeyklay** [comment]
We don't add changes directly to stable branches or `master`. Can you please do PR to `2.0.x` branch?

**Comment by sergeyklay** [comment]
Also update README.md please

**Comment by sergeyklay** [comment]
And what about `yaml`?

**Comment by Kachit** [comment]
Yaml adapter is full support but i dont have yaml extension

**Comment by sergeyklay** [comment]
Can you please do PR to `2.0.x` branch?

**Comment by Kachit** [comment]
of course

**Comment by Kachit** [comment]
I create new pull request to 2.0.x branch please delete this pull request

**Pull request closed without merging**
