### PR TITLE
[2.0.x] Removes no longer existing Adapters from README file

### PR DESCRIPTION
**Pull request by Green-Cat**

### CODE REVIEW

**Comment by sergeyklay** [comment]
Thanks

**Comment by sergeyklay** [comment]
@Green-Cat We can do something with bage for 2.0.x?

selection_046

**Comment by Green-Cat** [comment]
@sergeyklay There is no tag for 2.0.x

**Comment by sergeyklay** [comment]
@Green-Cat 2.0.x :smile_cat:

**Comment by Green-Cat** [comment]
Oh yes indeed, totally forgot about vpre.

**Pull request merged**
