### PR TITLE
V4.0.x upgrade

### PR DESCRIPTION
**Pull request by ruudboon**
Used http://php-pds.com/ structure
Fixed interfaces
Skipped a few test to make sure test suite can be run.

After integration I would like to automate the test and start upgrading every component.

Closes: https://github.com/phalcon/incubator/issues/919

### CODE REVIEW

**Comment by sergeyklay** [comment]
https://travis-ci.org/phalcon/incubator/jobs/578747239#L610

> PHP Warning:  Cannot load module 'phalcon' because required module 'psr' is not loaded in Unknown on line 0

**Comment by ruudboon** [comment]
@sergeyklay Didn't look into Travis yet. I prefer to this in a separate pull with issue #919 If @SidRoberts doesn't have time I can do this monday

**Comment by SidRoberts** [comment]
@ruudboon I was hoping that I'd have time this weekend but, unfortunately, I don't. :disappointed:

**Comment by ruudboon** [comment]
@SidRoberts No worries. Let's see who go time first. And ping each other on discord to make sure we're not doing it twice.

**Pull request closed without merging**
