### PR TITLE
Add eager loading

### PR DESCRIPTION
**Pull request by stibiumz**

### CODE REVIEW

**Comment by sergeyklay** [comment]
You rock! :+1:

**Comment by sergeyklay** [comment]
@stibiumz

**Comment by stibiumz** [comment]
> WARNING | Line exceeds 120 characters; contains 149 characters

Is that the problem now?

**Comment by sergeyklay** [comment]
Yes, please fix last issue.

**Comment by stibiumz** [comment]
Done

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
