### PR TITLE
add config loader factory

### PR DESCRIPTION
**Pull request by Kachit**

### CODE REVIEW

**Comment by sergeyklay** [comment]
This PR need rebase to `origin/2.0.x`

**Comment by sergeyklay** [comment]
Best way:
1. `git clone git@github.com:phalcon/incubator.git`
2. `cd incubator`
3. `git checkout 2.0.x` // **important**
5. _changes_
6. commit
7. push

**Comment by Kachit** [comment]
thanks

**Comment by sergeyklay** [comment]
Also could you please rebase and squash it into a single commit to keep the history clean? Let me know if you need instructions.

**Pull request closed without merging**
