### PR TITLE
Scrutinizer support

### PR DESCRIPTION
**Pull request by iGusev**
Pull request adds support scrutinizer and new badges with code coverage and code quality.

Also, please add the project to the Scrutinizer for the correct work of badges.

Example with my fork:
[Latest Version](https://github.com/phalcon/incubator/releases) [Software License](LICENSE.md) [Build Status](https://travis-ci.org/iGusev/incubator) [Coverage Status](https://scrutinizer-ci.com/g/iGusev/incubator/code-structure) [Quality Score](https://scrutinizer-ci.com/g/phalcon/incubator) [Total Downloads](https://packagist.org/packages/phalcon/incubator)

More info about scrutinizer [here](https://scrutinizer-ci.com/tour/measure-and-improve-code-quality).

### CODE REVIEW

**Comment by sergeyklay** [comment]
Thanks

**Comment by sergeyklay** [comment]
@andresgutierrez Add please Scrutinizer support

**Comment by andresgutierrez** [comment]
How they calculate code quality?

**Comment by iGusev** [comment]
Scrutinizer has three main metrics:
1. [Cyclomatic complexity](http://en.wikipedia.org/wiki/Cyclomatic_complexity)
2. Сode duplication
3. Size of class/function
4. (optional) Code coverage

Additional factors:
+ quality of documentation
+ static code analysis
+ best practices
+ cohesion of code

You can find more info in [docs](https://scrutinizer-ci.com/docs/) and their [blog](https://scrutinizer-ci.com/blog/)

A lot of libraries ([phpleague](http://thephpleague.com/) for example) are using these metrics.

**Comment by sergeyklay** [comment]
@andresgutierrez ping :)

**Pull request merged**
