### PR TITLE
Update UnitTestCase::checkExtension

### PR DESCRIPTION
**Pull request by sergeyklay**

### CODE REVIEW

**Comment by iGusev** [comment]
I think this method is not needed, because in phpunit you can do this:
```php
/**
  * @requires extension memcached
  */
public function testSomeMethodWithMemcached()
{
```

**Comment by sergeyklay** [comment]
@iGusev  this used here:

```php
abstract class UnitTestCase extends \PHPUnit_Framework_TestCase
{
    protected function setUp(DiInterface $di = null, Config $config = null)
    {
        $this->checkExtension('phalcon');
        // ...
    }
}
```

**Comment by sergeyklay** [comment]
@andresgutierrez  Your opinion?

**Comment by sergeyklay** [comment]
@iGusev It seems your suggestion throws error, but  `UnitTestCase::checkExtension` just mark test skipped

**Comment by iGusev** [comment]
@sergeyklay No, this annotation also skips the test (or whole class).
[Chapter 7. Incomplete and Skipped Tests](https://phpunit.de/manual/current/en/incomplete-and-skipped-tests.html)

`$this->markTestSkipped()` and `@requires` do the same things, but i think that "less code == less problems" :)

**Comment by iGusev** [comment]
Oh, you are right. I thought that the `@requires` is inherited from parent class, but it does not works =\
Only the `$this->markTestSkipped()` is a possible way to check extension in child classes.

**Pull request merged**
