### PR TITLE
Phalcon/Acl/Adapter/Database function isAllowd single quotes misuse

### PR DESCRIPTION
**Pull request by lisong**
This PR need rebase onto 2.0.x branch

### CODE REVIEW

**Comment by sergeyklay** [comment]
Could you please submit just the commits that belong to the PR? This PR need rebase onto `2.0.x` branch.

**Comment by lisong** [comment]
is that ok now ? sorry, first time do something

**Comment by sergeyklay** [comment]
@lisong Firstly I suggest use `Dialect`:
```sh
$ php -r 'echo (new Phalcon\Db\Dialect\Mysql)->escape("some_string"), PHP_EOL;'
`some_string`
```

You can get Dialect from connection.
Then create please your changes in your `2.0.x` on in `master` and send PR to the `2.0.x` branch

**Comment by lisong** [comment]
got it

**Comment by lisong** [comment]
$this->connection->getDialect() return a object implements \Phalcon\Db\AdapterInterface which didn't declare escape function; could I use $this->connection->escapeIdentifier('some_string') instead direct ?

**Comment by lisong** [comment]
my pool english, first i miss "Could you please submit just the commits that belong to the PR? This PR need rebase onto 2.0.x branch." ^_^

**Pull request closed without merging**
