### PR TITLE
Refactor deprecated Twig_Function_Method to Twig_SimpleFunction

### PR DESCRIPTION
**Pull request by kristoftorfs**
Hello!

* Type: bug fix
* Link to issue: N/A

This pull request affects the following components: **(please check boxes)**

* [X] Library
* [ ] Code Style
* [ ] Documentation
* [ ] Testing

**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/incubator/blob/master/CONTRIBUTING.md)?
- [X] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change:

Twig_Function_Method has been deprecated since version 1.12

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
We don't add changes directly to stable branches or `master`. Could you please send this PR to the `3.0.x` branch?

**Comment by kristoftorfs** [comment]
> Could you please send this PR to the 3.0.x branch?

Apologies, just changed the branch.

**Comment by sergeyklay** [comment]
@kristoftorfs Could you please take a look

**Comment by kristoftorfs** [comment]
Don't really get why the CI build failed, mine worked...

**Comment by sergeyklay** [comment]
@kristoftorfs 
The `3.0.x` branch is not longer supported. Could you please submit PR to the 3.1.x branch?

**Comment by kristoftorfs** [comment]
I am closing this and starting a clean PR.

**Pull request closed without merging**
