### PR TITLE
Database translate adapter (Optional ICU MessageFormatter)

### PR DESCRIPTION
**Pull request by YerlenZhubangaliyev**
ICU MessageFormatter

### CODE REVIEW

**Comment by sergeyklay** [comment]
Could you please squash it into a single commit to keep the history clean? Let me know if you need instructions.

**Comment by YerlenZhubangaliyev** [comment]
I need some instructions :)

**Comment by sergeyklay** [comment]
An easy way to use `git rebase -i HEAD~COMMIT_NUMBER_HERE` to squash commits. For example:

 `git rebase -i HEAD~3` 

https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/
https://davidwalsh.name/squash-commits-git

**Comment by YerlenZhubangaliyev** [comment]
done

**Comment by sergeyklay** [comment]
I'm not sure :)
selection_161

**Comment by YerlenZhubangaliyev** [comment]
I have some trouble with git squashing :(
I created a new PR

**Pull request closed without merging**
