### PR TITLE
Config loader dir

### PR DESCRIPTION
**Pull request by Kachit**

### CODE REVIEW

**Comment by sergeyklay** [comment]
Can you please squash into one commit?

**Comment by Kachit** [comment]
Hello @sergeyklay I have some problem with squash commits. Please give me simple manual ("for dummies") for this action

**Comment by sergeyklay** [comment]
For example https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by Kachit** [comment]
Oh. Im so sorry. I will merge this pr on this weekend

**Comment by sergeyklay** [comment]
@Kachit Hello. Thank you for contributing. As you can see this PR has conflicts. So this PR need to rebase. Also I have to notice that the 2.0.x branch is no longer supported. Could you please resend this PR to the 2.1.x branch?

**Comment by Kachit** [comment]
Hello I will close this PR and open new based on 2.1.x

**Pull request closed without merging**
