### PR TITLE
[2.0.x] Travis now checks against Phalcon 2.0.0 and 2.0.x.

### PR DESCRIPTION
**Pull request by SidRoberts**
All classes that became part of Phalcon 2 have also been deleted.

### CODE REVIEW

**Comment by sergeyklay** [comment]
:+1:

**Comment by iGusev** [comment]
Not all developers switched to version 2.0.x. :c

**Comment by sergeyklay** [comment]
@SidRoberts 
1. Can you leave 1.x branch (do not delete). Just add 2.x
2. It seems for 2.x version we have CI errors

**Comment by SidRoberts** [comment]
@sergeyklay Done. What do you want to do with classes like Debug\Dump that exist in incubator and cphalcon?

**Comment by sergeyklay** [comment]
@SidRoberts It seems we need delete from 2.x branch all existent classes for cphalcon

**Comment by SidRoberts** [comment]
@sergeyklay I'm going to start deleting classes/tests until Travis passes. I've just realised, if incubator/2.0.x is for Phalcon 2.0.0/2.0.x, why test against Phalcon 1.*?

**Comment by sergeyklay** [comment]
@SidRoberts Yes, you're right.  It's my bad. In this case 1.* not needed for Incubator 2.x

**Comment by SidRoberts** [comment]
[There's only 1 failure left](https://travis-ci.org/phalcon/incubator/jobs/61125050#L1317). It will get fixed once https://github.com/phalcon/cphalcon/pull/10226 is merged into 2.0.x but 2.0.0 will still fail. Delete the test method?

**Comment by sergeyklay** [comment]
We can temporary skip this test method for 2.0.0 and 2.0.x?

**Comment by SidRoberts** [comment]
@sergeyklay All done. :)

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
