### PR TITLE
Add Explicit and Implicit Deep Inherits to Phalcon\Acl\Adapter\Redis::addInherit

### PR DESCRIPTION
**Pull request by baychae**
Hello!

Type: new feature
Small description of change:

I have provisioned in the adapter for the following use of the adapter:

            //Add Inherits Explicit
            $inherits = [
                'user' => ['guest'],
                'poweruser' => ['user','guest'],
                'admin' => ['poweruser', 'user', 'guest'],
                'sysadmin' => ['admin','poweruser','user','guest']
            ];

            foreach ($inherits as $inherit => $base) {
                $acl->addInherit($inherit, $base);
            }

            //Add Inherits Implicit
            $inherits = [
                'user' => 'guest',
                'poweruser' => 'user',
                'admin' => 'poweruser',
                'sysadmin' => 'admin'
            ];

            foreach ($inherits as $inherit => $base) {
                $acl->addInherit($inherit, $base);
            }

Inherits will now allow deep inherits as in \Phalcon\Acl\Adapter\Memory.

This is a quick win as it is already provision for in Phalcon\Acl\Adapter\Redis::isAllowed.

Thanks

### CODE REVIEW

**Comment by sergeyklay** [comment]
@baychae Could you please update method phpdoc to add example usage

**Comment by baychae** [comment]
Is it possible to retest 561adeb? I think the build failure may be erroneous?

**Comment by baychae** [comment]
Examples in 561adeb.

**Comment by sergeyklay** [comment]
Thank you.


P.S. We don't add changes directly to stable branches or `master`. I changed the base branch to `3.2.x` from `master` just now.

**Comment by baychae** [comment]
That's awesome. Thanks so much!

**Pull request merged**
