### PR TITLE
[2.0.x] #300 Phalcon\Paginator\Pager::getPagesInRange() returned

### PR DESCRIPTION
**Pull request by endeveit**
@digitronac could you please look at this?
AFAIK it was your improvement i just copied it from 1.3 branch

### CODE REVIEW

**Comment by sergeyklay** [comment]
:100:

**Comment by sergeyklay** [comment]
Can merge?

**Comment by endeveit** [comment]
I think so. All tests were passed.

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
