### PR TITLE
Move Swiftmailer and Twig to Composer "suggest" block

### PR DESCRIPTION
**Pull request by CameronHall**
Hello!

* Type: code quality
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/incubator/blob/master/CONTRIBUTING.md)?
- [X] I have checked that another pull request for this purpose does not exist.

Small description of change: Fixes issue #875.

Thanks

### CODE REVIEW

**Comment by CameronHall** [comment]
@sergeyklay it looks like I've pulled in a couple other commits as a result of branching off of master (whoops...). Please let me know if this is an is an issue and I'll sort it out.

**Comment by sergeyklay** [comment]
@CameronHall You need to rebase `composer-dependency-update` branch on `3.4.x`. Or just create a new one from current `3.4.x` and cherry-pick 3dd369a

**Comment by CameronHall** [comment]
All done @sergeyklay

**Comment by sergeyklay** [comment]
Thank you

**Comment by sergeyklay** [comment]
Just released v3.4.3: https://github.com/phalcon/incubator/releases/tag/v3.4.3

**Pull request merged**
